services:
  postgres:
    image: postgres:16
    container_name: survey_platform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_platform
    ports:
      - "5433:5432"
    volumes:
      - survey_platform_pgdata:/var/lib/postgresql/data

volumes:
  survey_platform_pgdata:
